import React from 'react'
import Fade from "react-reveal/Fade";
import bootstrap from "./img/bootstrap.png";
import keeper from "./img/keeper.png";
import todo from "./img/todo.png";
import guess from "./img/Guess My Number.png";



export default function project() {
  return (
    <>
     <div className=" cont projcont col-xxl-8 px-4 pt-5" >
     <div className="row flex-lg-row-reverse align-items-center g-5 py-5">
        <Fade top duration={1500}>
      <div className="col-10 col-sm-8 col-lg-6">

        <img src={bootstrap} className="d-block mx-lg-auto img-fluid rounded" alt="Bootstrap Themes" width="700" height="500" loading="lazy"/>
      </div>
        </Fade>
        <Fade left >

      <div className="col-lg-6">
        <h1 className="display-5 fw-bold text-body-emphasis lh-2 mb-3">Bootstrap Framework</h1>
        <p className="lead">Here I used only the Bootstrap framework. wich is about dog selling web-site.</p>
        <div className="d-grid gap-2 d-md-flex justify-content-md-start">
        <a href="https://jeratos.github.io/bootstra-framework-website/" target='_blank' className="btn btn-primary pt-2 btn-lg px-4 me-md-2">Go to link</a>
        <a href="https://github.com/Jeratos/bootstra-framework-website" target='_blank' className="btn btn-outline-secondary pt-2 btn-lg px-4 ">Source Code</a>

        </div>
      </div>
        </Fade>
    </div>


    <div className="row flex-lg-row-reverse align-items-center g-5 py-5">
        <Fade top duration={1500}>
      <div className="col-10 col-sm-8 col-lg-6">

        <img src={keeper} className="d-block mx-lg-auto img-fluid rounded" alt="Bootstrap Themes" width="700" height="500" loading="lazy"/>
      </div>
        </Fade>
        <Fade left>

      <div className="col-lg-6">
        <h1 className="display-5 fw-bold text-body-emphasis lh-2 mb-3">Keeper App</h1>
        <p className="lead">It is similar to todo list. Here I used React library using hooks and props.</p>
        <div className="d-grid gap-2 d-md-flex justify-content-md-start">
        <a href="https://jeratos.github.io/reactDemoKeeperApp/" target='_blank' className="btn btn-primary pt-2 btn-lg px-4 me-md-2">Go to link</a>
        <a href="https://github.com/Jeratos/reactDemoKeeperApp" target='_blank' className="btn btn-outline-secondary pt-2 btn-lg px-4 ">Source Code</a>

        </div>
      </div>
        </Fade>
    </div>

    <div className="row flex-lg-row-reverse align-items-center g-5 py-5">
        <Fade top duration={1500}>
      <div className="col-10 col-sm-8 col-lg-6">

        <img src={todo} className="d-block mx-lg-auto img-fluid rounded" alt="Bootstrap Themes" width="700" height="500" loading="lazy"/>
      </div>
        </Fade>
        <Fade left>

      <div className="col-lg-6">
        <h1 className="display-5 fw-bold text-body-emphasis lh-2 mb-3">Todo App</h1>
        <p className="lead"> This is the todo list app, you can write here in the input 
          feald and after clicking the add button the text will be showing below.after adding the text
          you can delete it by clicking delete button.you can also line through the text by clicking on the text. 
          Here I also used the React JS library.</p>
        <div className="d-grid gap-2 d-md-flex justify-content-md-start">
        <a href="https://jeratos.github.io/todoApp-react/" target='_blank' className="btn btn-primary pt-2 btn-lg px-4 me-md-2">Go to link</a>
        <a href="https://github.com/Jeratos/todoApp-react" target='_blank' className="btn btn-outline-secondary pt-2 btn-lg px-4 ">Source Code</a>

        </div>
      </div>
        </Fade>
    </div>

    <div className="row flex-lg-row-reverse align-items-center g-5 py-5">
        <Fade top duration={1500}>
      <div className="col-10 col-sm-8 col-lg-6">

        <img src={guess} className="d-block mx-lg-auto img-fluid rounded" alt="Bootstrap Themes" width="700" height="500" loading="lazy"/>
      </div>
        </Fade>
        <Fade left>

      <div className="col-lg-6">
        <h1 className="display-5 fw-bold text-body-emphasis lh-2 mb-3">Guess The Number (Game)</h1>
        <p className="lead">this is the game where you guess the number wich is generated by randomly between 1 to 20  . And here I used Java Script to make the logic.</p>
        <div className="d-grid gap-2 d-md-flex justify-content-md-start">
        <a href=" https://jeratos.github.io/guessTheNumber/" target='_blank' className="btn btn-primary pt-2 btn-lg px-4 me-md-2">Go to link</a>
          {/* <button type="button" className="btn btn-outline-secondary btn-lg px-4">Default</button> */}
          <a href="https://github.com/Jeratos/guessTheNumber" target='_blank' className="btn btn-outline-secondary pt-2 btn-lg px-4 ">Source Code</a>
        </div>
      </div>
        </Fade>
    </div>
      </div> 
      
    </>
  )
}
